[theme]
name = "nord-dark"

[icons]
name = "awesome5"

[[block]]
block = "github"
format = "A:{author} | C:{comment} | M:{mention} | R:{review_requested}"
on_click = "firefox https://github.com/notifications"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "sound"
format = "{output_name} {volume}"
on_click = "toggle_pulse_sink"
[block.mappings]
"alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink" = "🔈"
"alsa_output.usb-Plantronics_Plantronics_BT600_e006012246d2dc419f7423a54ca2cb6f-00.analog-stereo" = "🎧🎤"
"bluez_sink.00_1B_66_B1_12_6C.a2dp_sink" = "🎧"

[[block]]
block = "time"
interval = 60
format = "%a %Y/%m/%d %R"
