[theme]
name = "gruvbox-dark"
[theme.overrides]

[icons]
name = "awesome"

#[[block]]
#block = "focused_window"
#max_width = 50
#show_marks = "visible"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"

[[block]]
block = "sound"
format = "{output_name} {volume}"
[block.mappings]
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "🔈"
"bluez_output.00_1B_66_88_12_79.a2dp-sink" = "🎧"
"bluez_output.E4_22_A5_90_13_B2.a2dp-sink" = "🎧"
"bluez_output.E4_22_A5_90_13_B2.headset-head-unit" = "🎧🎤"
"bluez_sink.58_FC_C6_4B_8C_06.a2dp_sink" = "👂💊"
"bluez_sink.58_FC_C6_4B_8C_06.handsfree_head_unit" = "👂💊🎤"

[[block]]
block = "time"
interval = 60
format = "%a %Y/%m/%d %R"

[[block]]
block = "net"
device = "wireless"
format = "{ssid} {signal_strength}"
