[theme]
theme = "gruvbox-dark"
[theme.overrides]

[icons]
icons = "awesome5"

[[block]]
block = "github"
format = "$icon A:$author C:$comment M:$mention R:$review_requested"
[[block.click]]
button = "left"
cmd = "xdg-open https://github.com/notifications"

[[block]]
block = "docker"
interval = 5
format = " $icon $running/$total "

[[block]]
block = "net"
device = "wlan0"
format = "$icon {$ssid} {$signal_strength}"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
driver = "upower"
interval = 10
format = "$icon $percentage $time"
missing_format = ""

[[block]]
block = "sound"
format = " $output_name{ $volume|} "
[block.mappings]
"alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink" = "🔈"
"bluez_output.00_1B_66_88_12_79.a2dp-sink" = "🎧"
"bluez_output.E4_22_A5_90_13_B2.a2dp-sink" = "🎧"
"alsa_output.usb-Plantronics_Plantronics_BT600_e006012246d2dc419f7423a54ca2cb6f-00.analog-stereo" = "🎧🎤"
"bluez_sink.58_FC_C6_4B_8C_06.a2dp_sink" = "👂💊"
"bluez_sink.58_FC_C6_4B_8C_06.handsfree_head_unit" = "👂💊🎤"
[[block.click]]
button = "right"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%a %Y/%m/%d %R')"
