[theme]
theme = "gruvbox-dark"
[theme.overrides]

[icons]
icons = "awesome5"

#[[block]]
#block = "github"
#format = "$icon A:$author C:$comment M:$mention R:$review_requested"
#[[block.click]]
#button = "left"
#cmd = "xdg-open https://github.com/notifications"

#[[block]]
#block = "docker"
#interval = 5
#format = " $icon $running/$total "

[[block]]
block = "net"
device = "wlan0"
format = "$icon {$ssid} {$signal_strength}"

#[[block]]
#block = "backlight"
#device = "intel_backlight"

[[block]]
block = "battery"
driver = "upower"
interval = 10
format = "$icon $percentage $time"
missing_format = ""

[[block]]
block = "time"
interval = 60
format = "$timestamp.datetime(f:'%a %Y/%m/%d %R')"
