
[icons]
# font awesome
firefox = ""
kitty = ""
slack = ""
deluge = ""
emacs = "⌨"
nheko = "🐈"
zotero = "📚"
calibre = "📚"
signal = "🔒"
psst = "🎶"
zoom = "📹"
discord = "💬"

[aliases]
Slack = "slack"
Deluge-gtk = "deluge"
Emacs = "emacs"
Zotero = "zotero"
Signal = "signal"
Psst-gui = "psst"
".*action=join.*" = "zoom"
".*launch?.*" = "zoom"
Discord = "discord"

[general]
separator = "  "
default_icon = ""
wm_property = "class"

[options]
remove_duplicates = true
no_names = false
no_icon_names = false
